name: Test Build

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  release:
    types:
      - published

jobs:
  build:
    name: Test ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64_cortex-a53
            runtime_test: false
          - arch: aarch64_cortex-a72
            runtime_test: false
          - arch: aarch64_cortex-a76
            runtime_test: false
          - arch: aarch64_generic
            runtime_test: true
          - arch: arm_cortex-a7_neon-vfpv4
            runtime_test: false
          - arch: arm_cortex-a9_vfpv3-d16
            runtime_test: false
          - arch: arm_cortex-a15_neon-vfpv4
            runtime_test: true
          - arch: i386_pentium4
            runtime_test: false
          - arch: mips_24kc
            runtime_test: true
          - arch: mipsel_24kc
            runtime_test: false
          - arch: riscv64_riscv64
            runtime_test: false
          - arch: x86_64
            runtime_test: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@v9
        env:
          ARCH: ${{ matrix.arch }}-openwrt-24.10
          FEEDNAME: packages_ci
          PACKAGES: cdnspeedtest
          V: s

      - name: Move created packages to project dir
        run: cp bin/packages/${{ matrix.arch }}/packages_ci/*.ipk . || true

      - name: Store packages
        uses: actions/upload-artifact@v4
        if: github.event_name != 'release'
        with:
          name: ${{ matrix.arch }}-${{ github.sha }}-packages
          path: "*.ipk"

      - name: Store logs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}-${{ github.sha }}-logs
          path: logs/

      - name: Upload packages
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ github.token }}
          file: "*.ipk"
          tag: ${{ github.ref }}
          file_glob: true

      - name: Remove logs
        run: sudo rm -rf logs/ || true

      - name: Register QEMU
        if: ${{ matrix.runtime_test }}
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo update-binfmts --import

      - name: Build Docker container
        if: ${{ matrix.runtime_test }}
        run: |
          docker build --platform linux/${{ matrix.arch }} -t test-container --build-arg ARCH .github/workflows/
        env:
          ARCH: ${{ matrix.arch }}-openwrt-24.10

      - name: Test via Docker container
        if: ${{ matrix.runtime_test }}
        run: |
          docker --platform linux/${{ matrix.arch }} run --rm -v $GITHUB_WORKSPACE:/ci test-container
